DROP DATABASE test1;

CREATE DATABASE test1;

USE test1;

CREATE TABLE tb_user (
  id VARCHAR(36) NOT NULL,
  username VARCHAR(20) NOT NULL,
  PASSWORD VARCHAR(16) NOT NULL,
  age INT(3) DEFAULT 0,
  create_time CHAR(20) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARSET=utf8